"""
#############################################################################
### Example Pydantic models file
###
### @file models_example.py
### @author Sebastian Russo
### @date 2026
#############################################################################

Template Pydantic models for a single entity, meant to be either deleted or
renamed/extended to fit the current project requirements.

The split below is a common, scalable pattern - keep it even when you rename
the entity:

    *Base      -> fields shared by every variant (the domain fields).
    *Create    -> what a client must send to create a record (POST body).
    *Update    -> what a client may send to patch a record (PATCH body);
                every field is Optional so partial updates work.
    *<Entity>  -> the full record as persisted, including server-managed
                fields such as ``id``.
    *Response  -> what the API returns. Kept separate from the stored model
                so you can hide internal fields later without touching it.
"""

#Native imports
from typing import Optional

#Third-party imports
from pydantic import BaseModel, Field


class ExampleItemBase(BaseModel):
    """
    Domain fields shared by every variant of the entity.

    Replace these with your own fields. ``Field(...)`` lets 
    you add validation/metadata (constraints, description, 
    examples) shown in the docs.
    """

    name: str = Field(..., min_length=1, description="Human-readable name.")
    description: Optional[str] = Field(
        default=None, description="Optional free-text description."
    )


class ExampleItemCreate(ExampleItemBase):
    """
    Payload accepted when creating a record (POST body).

    Inherits the domain fields from the base. The server 
    assigns the ``id``, so it is intentionally NOT part of
    this payload.
    """

    pass


class ExampleItemUpdate(BaseModel):
    """
    Payload accepted for partial updates (PATCH body).

    Every field is Optional; only the provided ones are
    applied. Mirror the editable fields of the base here 
    (omit anything that must stay immutable).
    """

    name: Optional[str] = Field(default=None, min_length=1)
    description: Optional[str] = None


class ExampleItem(ExampleItemBase):
    """
    The entity as stored in the data source, including
    server-managed fields.
    Inherits the domain fields from the base, and adds the
    ``id`` field which is generated by the server.
    """

    id: str = Field(..., description="Unique, server-generated identifier.")


class ExampleItemResponse(ExampleItem):
    """
    Response model returned by the API endpoints.

    Identical to the stored model today, but kept 
    separate so you can later add/remove response-only 
    fields (or hide internal ones) without changing 
    how records are persisted.
    """

    pass
